[Tests] [JSight to OpenAPI converter] req.japi.type_0.3
jsightapi/jsight-api-core pull request #14
Opened 2024-03-24 18:29 UTC by bereg2k

- Added new tests **for the requirement**: `req.japi.type_0.3`
- Added new tests **into the existing test files**: `regex_notation_in_directive_type`

2024-03-29 11:04 UTC, andrew-platonov requested changes

2024-03-29 11:04 UTC, andrew-platonov commented on testdata/jsight_0.3/ser-to-openapi/req.japi.type_0.3/user_type_or.openapi.todo
> +      "userType1SelfRef": {
Should be `userType1Self`

2024-03-29 17:12 UTC, bereg2k commented on testdata/jsight_0.3/ser-to-openapi/req.japi.type_0.3/user_type_basic.openapi.todo
> +      "cat": {
Replaced with `userTypeBasic`

2024-03-29 17:13 UTC, bereg2k commented on testdata/jsight_0.3/ser-to-openapi/req.japi.schema_notation/req.japi.schema_notation.regex_0.3/regex_notation_in_directive_type.openapi.todo
> +                  "oneOf": [
Understood, thanks! 

Fixed here.

2024-03-29 17:14 UTC, bereg2k commented on testdata/jsight_0.3/ser-to-openapi/req.japi.type_0.3/user_type_or.openapi.todo
> +      "userType1SelfRef": {
Fixed.

2024-03-30 07:42 UTC, andrew-platonov commented on testdata/jsight_0.3/ser-to-openapi/req.japi.type_0.3/user_type_basic.openapi.todo
> +      "cat": {
The content of the object is also wrong)

2024-03-30 18:43 UTC, bereg2k commented on testdata/jsight_0.3/ser-to-openapi/req.japi.type_0.3/user_type_basic.openapi.todo
> +      "cat": {
Fixed.

2024-04-01 07:25 UTC, merged